version: 0.2
phases:
  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - npm install
      - npm install react-router-dom
      - npm install react-icons
      - npm install styled-components
      - npm install express --save
      - npm install mysql --save
      - npm install pusher-js pushid
      - npm install cors dotenv newsapi --save
      - npm install env-cmd
      - npm install amazon-cognito-identity-js
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
    - .env
 
